# Generated by Django 2.1.7 on 2019-03-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=255, unique=True)),
                ('location', models.CharField(max_length=255)),
                ('battery', models.FloatField(blank=True, null=True)),
                ('bin_state', models.IntegerField(blank=True, null=True)),
                ('imei_code', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
            },
        ),
    ]
