# Generated by Django 2.1.7 on 2019-03-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wasco_app', '0002_auto_20190307_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicedata',
            name='device_id',
        ),
        migrations.RemoveField(
            model_name='devicelocation',
            name='device_id',
        ),
        migrations.AlterField(
            model_name='devicedata',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='devicelocation',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
