# Generated by Django 2.1.7 on 2019-03-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wasco_app', '0004_auto_20190307_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicedata',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='devicelocation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
