# Generated by Django 2.1.7 on 2019-03-11 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wasco_app', '0005_auto_20190307_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicelocation',
            name='location',
        ),
        migrations.AddField(
            model_name='devicelocation',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicelocation',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
