# Generated by Django 2.1.7 on 2019-03-14 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wasco_app', '0006_auto_20190311_1420'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicedata',
            options={'verbose_name': 'Device data', 'verbose_name_plural': 'Device data'},
        ),
        migrations.AlterModelOptions(
            name='devicelocation',
            options={'verbose_name': 'Device location', 'verbose_name_plural': 'Device location'},
        ),
        migrations.AddField(
            model_name='devicedata',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicedata',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
