# Generated by Django 2.1.7 on 2019-03-16 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wasco_app', '0007_auto_20190314_1301'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeviceLocation',
            new_name='DeviceSettings',
        ),
    ]
