# Generated by Django 2.1.7 on 2019-03-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wasco_app', '0009_auto_20190316_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicesettings',
            name='imei_code',
            field=models.CharField(max_length=255),
        ),
    ]
