# Generated by Django 2.1.7 on 2019-04-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wasco_app', '0010_auto_20190316_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicedata',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='devicesettings',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
